# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('reliability', ['core'])
    module.source = [
        'model/power-base.cc',
        'model/power-tracemodel.cc',
        'model/power-linearmodel.cc',
        'model/power-polynomialmodel.cc',
        'model/reliability-base.cc',
        'model/reliability-model.cc', 
        'model/temperature-base.cc',
        'model/temperature-model.cc',      
        'model/performance-model.cc',
        'helper/reliability-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('reliability')
    module_test.source = [
        'test/reliability-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'reliability'
    headers.source = [
        'model/power-base.h',
        'model/power-tracemodel.h',
        'model/power-linearmodel.h',
        'model/power-polynomialmodel.h',
        'model/reliability-base.h',
        'model/reliability-model.h', 
        'model/temperature-base.h',
        'model/temperature-model.h',
        'model/performance-model.h',
        'model/rapidcsv.h',      
        'helper/reliability-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

